name: Build daily JSON

on:
  schedule:
    # Runs every day at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch: {}

permissions:
  contents: write  # allow committing to the repo

jobs:
  build-json:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "1"
      # Optional: many tools honor TZ; Python naive datetimes won't automatically.
      TZ: Europe/Paris
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          fi

      - name: Run your generator
        # Replace with your real entry point
        run: |
          python UpdateTable.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore: daily JSON ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          else
            echo "No changes to commit."
          fi
